name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Generate Prisma Client
        run: pnpm dlx prisma generate --schema prisma/schema.prisma
      - run: pnpm lint && pnpm typecheck && pnpm --filter web test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: apps/web/coverage/lcov.info
          flags: web
          fail_ci_if_error: true
      - run: pnpm build

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RailwayApp/action@v3
        with:
          service: ${{ secrets.RAILWAY_SERVICE_ID }}
          envs: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
      - name: Run migrations
        run: pnpm prisma migrate deploy

